### PR TITLE
Add configurable github api endpoint

### PR DESCRIPTION
**Pull request by nwest1**
related to #33

### CODE REVIEW

**Comment by nwest1** [comment]
Let me know if you think there should be anything else added here. Thanks!

**Comment by jasonrudolph** [comment]
Thanks, @nwest1. I've pushed up a couple small changes, and I'm deploying this to our staging site to test it out. I'll post a follow-up reply once I finish testing.

**Comment by jasonrudolph** [comment]
I used the following test plan to verify the correctness of these changes, and everything is looking good:

- [x] Locally:
    - [x] Start the server and hit `http://localhost:3000/_ping`. Verify that the response body includes `"status":"ok"`.
    - [x] Set `GITHUB_API_URL` to point at a GitHub Enterprise instance (e.g., https://github-enterprise.example.com/api/v3/), start the server, and hit `http://localhost:3000/_ping`. Verify that the response body includes `"status":"ok"`.
- [x] On the staging server:
    - [x] Hit `/_ping` and verify that the response body includes `"status":"ok"`. (This confirms that the health check is still successfully communicating with api.github.com.)
    - [x] Open the Teletype settings in Atom and set the API server base URL to the staging server's URL. Reload Atom to pick up that change. Then, open the popover and verify that I see my avatar. (This confirms that the Atom package is able to ask the server for the GitHub identity associated with the given OAuth token, and that the server is able to successfully fetch the identity from the GitHub API.)

**Comment by jasonrudolph** [comment]
@as-cii: I think this is ready to merge, but I'd :heart: another review before we merge. Would you mind reviewing these changes?

**Comment by nwest1** [comment]
Thanks for the quick review!

I believe there's an edge case where an enterprise install can require authentication on the entire api. I will look at that later.

**Comment by nwest1** [comment]
Thanks! I'll submit another PR for the auth edge case which will be adding the ability to define an OAuth token or client credential (client_id/secret)

**Pull request merged**
