### PR TITLE
Add pusher.com cluster and github OAuth token configuration options

### PR DESCRIPTION
**Pull request by nwest1**
Pusher.com cluster config added: If you create your own pusher app, along with the appId and secrets, it also provides a cluster id. This integration has been tested manually. The default I chose, based on the atom package defaults,  is `mt1`

Github OAuth token added: in the event that Github enterprise has been configured to protect the entire API, creating a user-level OAuth token can be substituted for OAuth Client Credential-style (client_id, client_secret)

This leads me to question if the un-authenticated health check of the github api is used in a traditional deployment, why are the client_id and client_secret included in that request at all? Should that be removed?

### CODE REVIEW

**Comment by jasonrudolph** [comment]
@nwest1: Thanks for this contribution! :bow:

Even though [we don't have the resources to provide much support for people running their own server](https://github.com/atom/teletype-server/issues/33#issuecomment-344741440), I'm hopeful that we can incorporate these enhancements. It might take a while before we can review this pull request, but we'll review it as soon as we have time. :smile:

In the mean time, can you describe the test plan that you used to verify the correctness of these changes? In case it helps,  https://github.com/atom/teletype-server/pull/36#issuecomment-345392976 is the test plan I used for the previous pull request that we worked on together.

**Comment by nwest1** [comment]
Certainly! Happy to contribute towards making this something that people may run on their own. 

Test plan
- [x] Locally: (this assumes you have a working configuration)
  - [x] Startup server locally. Browse to `http://localhost:3000/_ping` verify body includes `"status":"ok"`. 
  - [x] Create pusher.com test account + application, use values pusher provides (app_id, key, secret, cluster.) Set the necessary env variables: `PUSHER_APP_ID` `PUSHER_KEY` `PUSHER_SECRET` `PUSHER_CLUSTER`. Restart teletype-server. Browse to `http://localhost:3000/_ping` and verify body includes `"status":"ok"`
   - [x] To verify negative, remove `PUSHER_CLUSTER`, restart teletype-server, browse to `http://localhost:3000/_ping`and verify body includes `"status":"failures"` and the key `failures` includes at least `pubSubGateway`
- [ ] Stage 
   - [ ] Verify server is up and running. Hit `/_ping` and verify body includes `"status":"ok"`. This confirms pusher.com is up and running, and configured properly.
  - [ ] Create pusher.com test account + application, use values pusher provides (app_id, key, secret, cluster.) Set the necessary env variables: `PUSHER_APP_ID` `PUSHER_KEY` `PUSHER_SECRET` `PUSHER_CLUSTER`. Restart teletype-server. Browse to `/_ping` and verify body includes `"status":"ok"`
   - [ ] To verify negative, remove `PUSHER_CLUSTER`, restart teletype-server, browse to `/_ping`and verify body includes `"status":"failures"` and the key `failures` includes at least `pubSubGateway`

**Comment by jasonrudolph** [comment]
> This leads me to question if the un-authenticated health check of the github api is used in a traditional deployment, why are the client_id and client_secret included in that request at all? Should that be removed?

The client ID and secret are needed to avoid exceeding the GitHub API rate limit. Without those credentials, if the `/_ping` endpoint were to receive more than 60 requests in an hour, it would exceed the GitHub API rate limit. By including these credentials, we avoid that issue. :sweat_smile:

https://developer.github.com/v3/#increasing-the-unauthenticated-rate-limit-for-oauth-applications

**Comment by jasonrudolph** [comment]
Thank you for sharing the test plan, @nwest1. :zap:

I've tested this out locally, and it's looking good. I'll try this out on the staging server next week.

**Comment by jasonrudolph** [comment]
I deployed this to the staging server, and everything looks good there as well. Thanks, @nwest1. :bow:

**Pull request merged**
